// JGG Skills Market — 66 entries grounded in owner screenshots S02–S08 (spec §5).
// Titles may be normalized; descriptions are JGG's own. Engagement counts are NOT shown (no real JGG analytics yet).
import type { CapabilityStatus } from '../../contracts/src/index.ts';

export type SkillCategory = 'Trading' | 'Data Analytics' | 'Monitor' | 'News & Media' | 'Cooking';
export type SkillSource = 'JGG' | '6551' | 'X';
export type Scope = 'market:read' | 'wallet:read' | 'signals:read' | 'watchlist:write' | 'trade:propose' | 'trade:execute' | 'strategy:manage' | 'launch:propose' | 'launch:execute';

export type InputField = { name: string; type: 'chain' | 'address' | 'wallet' | 'string' | 'decimal' | 'int' | 'enum' | 'bool'; required?: boolean; options?: string[]; default?: string | number | boolean; help?: string; min?: number; max?: number };

export type Skill = {
  id: string; version: string; title: string; icon: string; category: SkillCategory; source: SkillSource;
  summary: string; toolId: string; scopes: Scope[]; supportedChains: string[];
  inputs: InputField[]; dependencies: string[];
  /** status per operating mode */
  status: { demo: CapabilityStatus; paper: CapabilityStatus; live: CapabilityStatus };
  blocker?: string; outputExample: string; ref: string;
};

const ALL = ['solana', 'bsc', 'base', 'ethereum'];
const chain: InputField = { name: 'chain', type: 'chain', required: true, default: 'solana' };
const token: InputField = { name: 'address', type: 'address', required: true, help: 'Canonical contract/mint address (never a ticker).' };
const wallet: InputField = { name: 'wallet', type: 'address', required: true, help: 'Public wallet address.' };
const period = (opts = ['1m', '5m', '1h', '6h', '24h'], d = '1h'): InputField => ({ name: 'window', type: 'enum', options: opts, default: d });
const limit: InputField = { name: 'limit', type: 'int', default: 20, min: 1, max: 100 };
const minLiq: InputField = { name: 'minLiquidityUsd', type: 'decimal', help: 'Optional minimum pool liquidity (USD).' };
const minMc: InputField = { name: 'minMarketCapUsd', type: 'decimal' }; const maxMc: InputField = { name: 'maxMarketCapUsd', type: 'decimal' };
const smMin: InputField = { name: 'minSmartMoney', type: 'int', min: 0, max: 100, help: 'Wallets classified by the disclosed JGG fixture rule (demo) or provider label (live).' };

const READ = { demo: 'implemented_demo', paper: 'implemented_demo', live: 'blocked_external' } as const;
const TRADE = { demo: 'implemented_demo', paper: 'implemented_paper', live: 'blocked_external' } as const;
const EXT = { demo: 'implemented_demo', paper: 'implemented_demo', live: 'blocked_external' } as const;
const LIVE_READ_BLOCK = 'Live read requires a configured market/analytics provider credential (JGG_MARKET_PROVIDER_* or GMGN_API_KEY) and outbound network. Not available in this build environment.';
const LIVE_TRADE_BLOCK = 'Live execution requires a verified execution provider + policy-capable signer and explicit owner authorization for funded tests (T59).';

type Row = [id: string, title: string, icon: string, cat: SkillCategory, src: SkillSource, summary: string, tool: string, scopes: Scope[], inputs: InputField[], chains?: string[], extra?: Partial<Skill>];

const rows: Row[] = [
  ['C01', '5-Min Trending Tokens', '🔥', 'Data Analytics', 'JGG', 'Rank the most actively traded tokens over the last 5 minutes with liquidity, market-cap and holder filters; shows filter reasons and exact window bounds.', 'market.trending', ['market:read'], [chain, { ...period(['5m'], '5m') }, minLiq, minMc, maxMc, limit]],
  ['C02', 'Cross-Chain Curated Hot List', '🌶️', 'Data Analytics', 'JGG', 'Sweep supported chains for active tokens, gate each on liquidity, volume and concentration, and group comparable metrics by chain.', 'market.hotlist', ['market:read'], [{ name: 'minVolumeUsd', type: 'decimal', default: '10000' }, { ...minLiq, default: '5000' }, { name: 'maxTop10Bps', type: 'int', default: 5000, min: 0, max: 10000 }, limit], ALL],
  ['C03', 'Buy by Token Name (Copycat & Risk Check)', '🛒', 'Trading', 'JGG', 'Resolve every same-name candidate, require you to pick the canonical contract, run the risk check, then produce a sized quote and proposed order.', 'trade.buyByName', ['market:read', 'trade:propose'], [chain, { name: 'query', type: 'string', required: true, help: 'Name or ticker to resolve' }, { name: 'amount', type: 'decimal', required: true, default: '0.1' }, { name: 'slippageBps', type: 'int', default: 300, min: 1, max: 5000 }]],
  ['C04', 'Pump.fun Trending Tokens', '🏆', 'Data Analytics', 'JGG', 'Trending tokens attributed to the Pump.fun launchpad with lifecycle state (bonding / migrated) and numeric range filters.', 'market.launchpadTrending', ['market:read'], [{ ...chain, default: 'solana', options: ['solana'] }, period(['1h'], '1h'), minMc, maxMc, limit], ['solana']],
  ['C05', 'Token Due-Diligence Score', '🔬', 'Data Analytics', 'JGG', 'One 0–100 JGG rubric score (jgg-dd-v1) from contract safety, holder structure, tax and liquidity, with coverage and missing factors listed.', 'token.dd', ['market:read'], [chain, token]],
  ['C06', 'Wallet Analysis', '🧭', 'Data Analytics', 'JGG', 'Four evidence gates on a wallet: real record, recent edge, fillability of its sizes, and exit behaviour.', 'wallet.analysis', ['wallet:read'], [chain, wallet, period(['7d', '30d'], '30d')]],
  ['C07', 'Token Basic Info', '🪪', 'Data Analytics', 'JGG', 'Price, supply basis, market cap vs FDV, liquidity, holders, top-10 concentration (with denominator), dev exposure and links.', 'token.info', ['market:read'], [chain, token]],
  ['C08', 'Chart Pattern Read & Score', '🕯️', 'Data Analytics', 'JGG', 'Timestamped chart observations (trend channel, breakdown, base, distribution) with timeframe and invalidation level. No price prediction.', 'token.pattern', ['market:read'], [chain, token, { name: 'interval', type: 'enum', options: ['1m', '5m', '15m', '1h'], default: '5m' }]],
  ['C09', 'Dev Score', '🔨', 'Data Analytics', 'JGG', 'Two separate axes for a token creator: conduct (sold at open?) and track record (launch outcomes), with attribution limits.', 'dev.score', ['market:read'], [chain, { ...wallet, name: 'creator', help: 'Creator wallet' }]],
  ['C10', 'Pump.fun Newly Created Tokens', '🌱', 'Data Analytics', 'JGG', 'Fresh Pump.fun launches from launch events, filterable by smart-money count, bundle share and dev holding.', 'market.newTokens', ['market:read'], [{ ...chain, options: ['solana'] }, { name: 'launchpad', type: 'enum', options: ['pumpfun'], default: 'pumpfun' }, smMin, limit], ['solana']],
  ['C11', 'OpenTwitter MCP', '🕊️', 'News & Media', '6551', 'Optional 6551 social connector: profiles, tweet search, follower changes. Requires your own 6551 credential; source and entitlement disclosed.', 'social.query', ['signals:read'], [{ name: 'handle', type: 'string', required: true }], ALL, { status: EXT, blocker: 'Requires 6551 OpenTwitter credential (JGG_X_PROVIDER_*) and license review.' }],
  ['C12', 'OpenNews MCP', '📰', 'News & Media', '6551', 'Optional 6551 crypto news connector with links, timestamps and attribution. Requires your 6551 credential.', 'news.query', ['signals:read'], [{ name: 'topic', type: 'string', default: 'solana' }, limit], ALL, { status: EXT, blocker: 'Requires 6551 OpenNews credential (JGG_NEWS_PROVIDER_*).' }],
  ['C13', 'Market Buy', '⚡', 'Trading', 'JGG', 'Exact-input buy: current route, every fee component, minimum received, review/approval, then reconciliation of the actual fill.', 'trade.marketBuy', ['trade:propose', 'trade:execute'], [chain, token, { name: 'amount', type: 'decimal', required: true, default: '0.1' }, { name: 'slippageBps', type: 'int', default: 300, min: 1, max: 5000 }]],
  ['C14', 'Query 5m Hot Search Tokens', '🌡️', 'Data Analytics', 'JGG', 'Search-activity ranking over 1m/5m/1h/6h/24h. Uses search counts from a named source only — never substitutes trade volume.', 'market.hotSearch', ['market:read'], [chain, period(), limit], ALL, { blocker: 'Live needs a search-activity data source; JGG has no search telemetry yet. Demo uses labeled fixture counts.' }],
  ['C15', 'Bankr Newly Created Tokens', '🍀', 'Data Analytics', 'JGG', 'New Bankr launches on Base, filterable by smart-money count and bundle ratio. Provider availability verified separately.', 'market.newTokens', ['market:read'], [{ ...chain, default: 'base', options: ['base'] }, { name: 'launchpad', type: 'enum', options: ['bankr'], default: 'bankr' }, smMin, limit], ['base']],
  ['C16', 'Fourmeme Newly Created Tokens', '🌿', 'Data Analytics', 'JGG', 'New FourMeme launches on BSC with launchpad metadata and smart-money / bundle filters.', 'market.newTokens', ['market:read'], [{ ...chain, default: 'bsc', options: ['bsc'] }, { name: 'launchpad', type: 'enum', options: ['fourmeme'], default: 'fourmeme' }, smMin, limit], ['bsc']],
  ['C17', 'Newly Created Tokens', '🐣', 'Data Analytics', 'JGG', 'Unified feed across supported launchpads with deduplication and per-row source attribution.', 'market.newTokens', ['market:read'], [chain, { name: 'launchpad', type: 'enum', options: ['any'], default: 'any' }, smMin, limit]],
  ['C18', 'KOL-Bought New Tokens', '👑', 'Data Analytics', 'JGG', 'New tokens with observed buys by labeled KOL wallets; each label and buy event shows its evidence.', 'market.kolBought', ['market:read', 'signals:read'], [chain, { name: 'minKols', type: 'int', default: 1, min: 1, max: 50 }, limit]],
  ['C19', 'Migrated Tokens', '🎓', 'Data Analytics', 'JGG', 'Confirmed migration / DEX-opening events with old and new pool relationships, filterable by smart money and market cap.', 'market.migrated', ['market:read'], [chain, smMin, minMc, maxMc, limit]],
  ['C20', 'Migrated Token Quality Screener', '🔍', 'Data Analytics', 'JGG', 'Post-migration screen with a saved preset (MC $50K–$200K, liquidity > $10K, top-10 < 30% by default) and a factor-by-factor decision.', 'market.migratedScreen', ['market:read'], [chain, { ...minMc, default: '50000' }, { ...maxMc, default: '200000' }, { ...minLiq, default: '10000' }, { name: 'maxTop10Bps', type: 'int', default: 3000, min: 0, max: 10000 }]],
  ['C21', 'Near Completion Tokens', '🌗', 'Data Analytics', 'JGG', 'Bonding-curve progress read from the specific launchpad protocol; no invented universal graduation threshold.', 'market.nearCompletion', ['market:read'], [chain, { name: 'minProgressBps', type: 'int', default: 8000, min: 0, max: 10000 }, smMin, limit]],
  ['C22', 'Token Security Check', '🛡️', 'Data Analytics', 'JGG', 'Chain-specific security observations — honeypot, authorities, open source, LP lock, buy/sell tax — each safe / risky / unknown / n/a.', 'token.security', ['market:read'], [chain, token]],
  ['C23', 'Token Kline Data', '📊', 'Data Analytics', 'JGG', 'OHLCV with time bounds, source pool, currency, interval and explicit gap markers. Sub-minute intervals only from trade aggregation.', 'token.kline', ['market:read'], [chain, token, { name: 'interval', type: 'enum', options: ['1m', '5m', '15m', '1h', '4h', '1d'], default: '5m' }, { name: 'count', type: 'int', default: 120, min: 10, max: 1000 }]],
  ['C24', 'Dev Info Analysis', '🧐', 'Data Analytics', 'JGG', 'Creator holdings, launch history, best ATH, funding links and observed social changes — with attribution limits stated.', 'dev.info', ['market:read'], [chain, token]],
  ['C25', 'Liquidity Pool Analysis', '💧', 'Data Analytics', 'JGG', 'Pools, reserves/depth, DEX, quote asset, fee tier where known, pool creation time and LP lock evidence.', 'token.pools', ['market:read'], [chain, token]],
  ['C26', 'Top 100 Holders Analysis', '👥', 'Data Analytics', 'JGG', 'Up to 100 holders with share, value, basis and labels; excluded system addresses and supply denominator shown.', 'token.holders', ['market:read'], [chain, token, { ...limit, default: 100 }]],
  ['C27', 'Top 100 Traders Analysis', '🥇', 'Data Analytics', 'JGG', 'Up to 100 traders ranked by the chosen metric with buy/sell volume, trade count, realized P&L and coverage.', 'token.traders', ['market:read'], [chain, token, { name: 'sortBy', type: 'enum', options: ['realized_pnl', 'volume', 'trades'], default: 'realized_pnl' }]],
  ['C28', 'Dev Created Tokens', '👨‍🍳', 'Data Analytics', 'JGG', 'All tokens attributed to a creator wallet with ATH and current market cap and observed migration outcome.', 'dev.tokens', ['market:read'], [chain, { ...wallet, name: 'creator' }]],
  ['C29', 'Smart Money Holders Analysis', '🧠', 'Data Analytics', 'JGG', 'Holdings of wallets classified as smart money under a disclosed rule version: share, value, basis and P&L.', 'token.labeledHolders', ['market:read'], [chain, token, { name: 'label', type: 'enum', options: ['smart_money'], default: 'smart_money' }]],
  ['C30', 'KOL Holders Analysis', '🌟', 'Data Analytics', 'JGG', 'Holdings of labeled KOL wallets with attribution and freshness.', 'token.labeledHolders', ['market:read'], [chain, token, { name: 'label', type: 'enum', options: ['kol'], default: 'kol' }]],
  ['C31', 'Tracked Wallet Trades', '❤️', 'Monitor', 'JGG', 'Buy/sell events from the wallets you follow in JGG, with token, amount, price and chain transaction link.', 'signals.walletTrades', ['signals:read'], [chain, { name: 'side', type: 'enum', options: ['all', 'buy', 'sell'], default: 'all' }, limit]],
  ['C32', 'KOL Trades', '📡', 'Monitor', 'JGG', 'Observed trade events for labeled KOL wallets with buy/sell filter and current price.', 'signals.labelTrades', ['signals:read'], [chain, { name: 'label', type: 'enum', options: ['kol'], default: 'kol' }, { name: 'side', type: 'enum', options: ['all', 'buy', 'sell'], default: 'all' }, limit]],
  ['C33', 'Smart Money Trades', '👁️', 'Monitor', 'JGG', 'Observed trade events for the selected smart-money universe and rule version.', 'signals.labelTrades', ['signals:read'], [chain, { name: 'label', type: 'enum', options: ['smart_money'], default: 'smart_money' }, { name: 'side', type: 'enum', options: ['all', 'buy', 'sell'], default: 'all' }, limit]],
  ['C34', 'KOL Call Signal', '📣', 'Monitor', 'JGG', 'Source-backed callouts with author, time, canonical asset and the observed price move afterwards (not follower profit).', 'signals.callouts', ['signals:read'], [chain, limit]],
  ['C35', 'Query Watchlist Tokens', '⭐', 'Monitor', 'JGG', 'Your own watchlist groups with current price, change and volume. Never another user’s list.', 'watchlist.query', ['watchlist:write', 'market:read'], [{ name: 'group', type: 'string', help: 'Watchlist name (optional)' }]],
  ['C36', 'Scan Watchlist Price Swings', '🔔', 'Monitor', 'JGG', 'Threshold swings over an explicit window with cooldown and data freshness, across your watchlist.', 'watchlist.swings', ['watchlist:write', 'market:read'], [{ name: 'thresholdBps', type: 'int', default: 1000, min: 1, max: 100000 }, period(['5m', '1h', '24h'], '1h')]],
  ['C37', 'Pump Claim Signal', '🎁', 'Monitor', 'JGG', 'Protocol-defined claim events on Pump.fun with beneficiary, amount and type. Not assumed to be an airdrop.', 'signals.claims', ['signals:read'], [{ ...chain, options: ['solana'] }, limit], ['solana']],
  ['C38', 'Smart Money Buy Signal', '💰', 'Monitor', 'JGG', 'Cluster buys by distinct qualifying wallets within a window, with overlap assumptions shown.', 'signals.cluster', ['signals:read'], [chain, { name: 'side', type: 'enum', options: ['buy'], default: 'buy' }, { name: 'minWallets', type: 'int', default: 3, min: 2, max: 50 }, period(['5m', '1h'], '1h')]],
  ['C39', 'Price Surge Signal', '💹', 'Monitor', 'JGG', 'Timestamped price/volume surge events with the comparison baseline.', 'signals.surge', ['signals:read'], [chain, { name: 'minChangeBps', type: 'int', default: 2000, min: 100, max: 1000000 }, period(['1m', '5m'], '5m')]],
  ['C40', 'Price Surge Signal Token Screening', '🚀', 'Monitor', 'JGG', 'Surge detection composed with security, concentration and liquidity checks into a reviewable per-token result.', 'signals.surgeScreen', ['signals:read', 'market:read'], [chain, { name: 'minChangeBps', type: 'int', default: 2000, min: 100, max: 1000000 }]],
  ['C41', 'Smart Money Exit Signal', '🚨', 'Monitor', 'JGG', 'Clustered selling by smart-money wallets and their remaining exposure. No guarantee of early warning.', 'signals.cluster', ['signals:read'], [chain, { name: 'side', type: 'enum', options: ['sell'], default: 'sell' }, { name: 'minWallets', type: 'int', default: 3, min: 2, max: 50 }, period(['5m', '1h'], '1h')]],
  ['C42', 'Twitter — Get Following Posts', '🐦', 'News & Media', 'X', 'Your X following timeline via your own authorized X API access; pagination and content types as permitted.', 'social.following', ['signals:read'], [limit], ALL, { status: EXT, blocker: 'Requires user-authorized X API access (OAuth) under X terms.' }],
  ['C43', 'Wallet P&L Stats', '💵', 'Data Analytics', 'JGG', 'Period P&L, win rate (with denominator), trade count and accounting coverage for 7d / 30d.', 'wallet.pnl', ['wallet:read'], [chain, wallet, period(['7d', '30d'], '7d')]],
  ['C44', 'Wallet Holdings', '💎', 'Data Analytics', 'JGG', 'Current balances, mark values, known basis and realized/unrealized split per token.', 'wallet.holdings', ['wallet:read'], [chain, wallet]],
  ['C45', 'Wallet Trade History', '📝', 'Data Analytics', 'JGG', 'Normalized buys, sells and transfers with original chain references and cursor pagination.', 'wallet.history', ['wallet:read'], [chain, wallet, { name: 'type', type: 'enum', options: ['all', 'buy', 'sell', 'transfer'], default: 'all' }, limit]],
  ['C46', 'Wallet Token Balance', '🏛️', 'Data Analytics', 'JGG', 'Raw amount plus decimals and display amount at a recorded slot/block.', 'wallet.tokenBalance', ['wallet:read'], [chain, wallet, token]],
  ['C47', 'Wallet Copy Trade Assessment', '⚖️', 'Data Analytics', 'JGG', 'Historical copy suitability: concentration, lag sensitivity, fees, fillability and sample size.', 'wallet.copyAssessment', ['wallet:read'], [chain, wallet]],
  ['C48', 'Wallet Address Score', '🧮', 'Data Analytics', 'JGG', 'Three separate dimensions — profitability record, copy feasibility, risk — on a versioned rubric.', 'wallet.score', ['wallet:read'], [chain, wallet]],
  ['C49', 'Market Sell', '💸', 'Trading', 'JGG', 'Sell an amount or an explicit holdings percentage; balance reservation, quote, approval and execution result.', 'trade.marketSell', ['trade:propose', 'trade:execute'], [chain, token, { name: 'percentBps', type: 'int', default: 10000, min: 1, max: 10000 }, { name: 'slippageBps', type: 'int', default: 300, min: 1, max: 5000 }]],
  ['C50', 'Multi-Wallet Buy', '🔱', 'Trading', 'JGG', 'Batch buy from up to 100 of your wallets with independent amounts and per-child results. Never atomic.', 'trade.multiWalletBuy', ['trade:propose', 'trade:execute'], [chain, token, { name: 'amountEach', type: 'decimal', default: '0.05' }, { name: 'wallets', type: 'int', default: 2, min: 1, max: 100, help: 'Number of your paper wallets' }]],
  ['C51', 'Query Real-Time Gas Price', '⛽', 'Trading', 'JGG', 'Network-specific fee estimates: Solana priority fee (micro-lamports/CU) vs EVM gas (gwei) — never mixed.', 'chain.fees', ['market:read'], [chain]],
  ['C52', 'Limit Buy', '⏳', 'Trading', 'JGG', 'Monitored limit buy: triggers when the eligible price is at or below target, requotes and enforces the effective-price bound.', 'strategy.limitBuy', ['strategy:manage'], [chain, token, { name: 'targetPrice', type: 'decimal', required: true }, { name: 'amount', type: 'decimal', required: true, default: '0.1' }, { name: 'expiresInSec', type: 'int', default: 86400, min: 60, max: 2592000 }]],
  ['C53', 'Limit Buy with TP/SL Strategy Order', '🤖', 'Trading', 'JGG', 'Parent limit entry with dormant exits that activate only for the actually confirmed fill quantity.', 'strategy.limitBuyTpSl', ['strategy:manage'], [chain, token, { name: 'targetPrice', type: 'decimal', required: true }, { name: 'amount', type: 'decimal', required: true, default: '0.1' }, { name: 'takeProfit', type: 'decimal', default: '0.5', help: 'Gain fraction' }, { name: 'stopLoss', type: 'decimal', default: '0.25', help: 'Loss fraction' }]],
  ['C54', 'Limit Sell', '🎯', 'Trading', 'JGG', 'Monitored limit sell at or above target with reserved/available quantity shown.', 'strategy.limitSell', ['strategy:manage'], [chain, token, { name: 'targetPrice', type: 'decimal', required: true }, { name: 'percentBps', type: 'int', default: 10000, min: 1, max: 10000 }]],
  ['C55', 'Buy with Take Profit & Stop Loss', '🦺', 'Trading', 'JGG', 'Entry plus staged exits (percent of ORIGINAL fill) and a protective stop, activated durably after fill.', 'strategy.buyTpSl', ['trade:propose', 'strategy:manage'], [chain, token, { name: 'amount', type: 'decimal', required: true, default: '0.1' }, { name: 'takeProfit', type: 'decimal', default: '1' }, { name: 'stopLoss', type: 'decimal', default: '0.3' }]],
  ['C56', 'Trailing Take Profit', '📈', 'Trading', 'JGG', 'Activates at E×(1+a), tracks a stored peak H, triggers once at H×(1−d). Peak persists across restarts.', 'strategy.trailingTp', ['strategy:manage'], [chain, token, { name: 'activation', type: 'decimal', default: '0.2' }, { name: 'retracement', type: 'decimal', default: '0.1' }]],
  ['C57', 'Trailing Stop Loss', '📉', 'Trading', 'JGG', 'Stop trails the high-water mark from entry and never moves down within its epoch; restart-safe.', 'strategy.trailingSl', ['strategy:manage'], [chain, token, { name: 'retracement', type: 'decimal', default: '0.15' }]],
  ['C58', 'Query Open Orders', '📋', 'Trading', 'JGG', 'Your open entries, exits and strategies with IDs, trigger, state, expiry and cancellation status.', 'orders.open', ['trade:propose'], [{ name: 'chain', type: 'chain', default: 'solana' }]],
  ['C59', 'Cancel Strategy Order', '⛔', 'Trading', 'JGG', 'Authorized cancellation with a race-safe result. Submitted blockchain trades cannot be undone — reports CANCEL_TOO_LATE.', 'orders.cancel', ['strategy:manage'], [{ name: 'orderId', type: 'string', required: true }]],
  ['C60', 'Query Launchpad Stats', '📁', 'Cooking', 'JGG', 'Launch counts by protocol/time/chain, separating JGG-created launches from provider-wide statistics.', 'launch.stats', ['market:read'], [chain, period(['24h', '7d'], '24h')]],
  ['C61', 'Launch on Pump.fun', '💊', 'Cooking', 'JGG', 'Validated Pump.fun launch form → protocol-specific preparation → explicit signing → launch receipt.', 'launch.create', ['launch:propose', 'launch:execute'], [{ name: 'launchpad', type: 'enum', options: ['pumpfun'], default: 'pumpfun' }], ['solana']],
  ['C62', 'Launch on FourMeme', '🧤', 'Cooking', 'JGG', 'BSC FourMeme launch using a verified current contract/SDK integration.', 'launch.create', ['launch:propose', 'launch:execute'], [{ name: 'launchpad', type: 'enum', options: ['fourmeme'], default: 'fourmeme' }], ['bsc']],
  ['C63', 'Launch on Clanker', '📶', 'Cooking', 'JGG', 'Base Clanker launch using a verified current contract/SDK integration.', 'launch.create', ['launch:propose', 'launch:execute'], [{ name: 'launchpad', type: 'enum', options: ['clanker'], default: 'clanker' }], ['base']],
  ['C64', 'Launch Tax Token on FourMeme', '🧾', 'Cooking', 'JGG', 'FourMeme tax token: supported buy/sell tax, recipients and allocation validation; effective tax disclosed.', 'launch.create', ['launch:propose', 'launch:execute'], [{ name: 'launchpad', type: 'enum', options: ['fourmeme_tax'], default: 'fourmeme_tax' }], ['bsc']],
  ['C65', 'Launch on Pump.fun — Cashback / Auto Buyback', '🔄', 'Cooking', 'JGG', 'Special Pump.fun launch modes. Enabled only after exact names, exclusivity and parameters are verified (reference title was truncated).', 'launch.create', ['launch:propose', 'launch:execute'], [{ name: 'launchpad', type: 'enum', options: ['pumpfun_special'], default: 'pumpfun_special' }], ['solana'], { blocker: 'Mode semantics unverified (S08 card truncated). Form accepts drafts only.' }],
  ['C66', 'Launch Tax Token on Flap', '🏷️', 'Cooking', 'JGG', 'Flap (BSC) tax token with verified tax/recipient semantics. Missing details from the cropped reference are not invented.', 'launch.create', ['launch:propose', 'launch:execute'], [{ name: 'launchpad', type: 'enum', options: ['flap_tax'], default: 'flap_tax' }], ['bsc'], { blocker: 'Flap tax semantics unverified (S08 cropped). Drafts only.' }],
];

export const SKILLS: Skill[] = rows.map(([id, title, icon, category, source, summary, toolId, scopes, inputs, chains, extra]) => {
  const isTrade = category === 'Trading' && !toolId.startsWith('chain.') && !toolId.startsWith('orders.open');
  const isLaunch = category === 'Cooking' && toolId === 'launch.create';
  const isSocial = toolId.startsWith('social.') || toolId.startsWith('news.'); // needs X/6551/news provider in every mode — never fabricated
  const status = extra?.status ?? (isSocial ? { demo: 'blocked_external', paper: 'blocked_external', live: 'blocked_external' } as const : isTrade ? TRADE : isLaunch ? { demo: 'implemented_demo', paper: 'implemented_demo', live: 'blocked_external' } as const : READ);
  return {
    id, version: '1.0.0', title, icon, category, source, summary, toolId, scopes, inputs,
    supportedChains: chains ?? ALL,
    dependencies: isTrade ? ['ExecutionProvider', 'SignerProvider', 'MarketDataProvider'] : isLaunch ? ['LaunchProvider', 'SignerProvider'] : source !== 'JGG' ? ['SocialProvider'] : ['MarketDataProvider'],
    status: { ...status },
    blocker: extra?.blocker ?? (isSocial ? 'Requires an authorized X API / 6551 OpenTwitter / licensed news provider + credentials. Not configured; JGG returns CAPABILITY_BLOCKED instead of invented posts.' : isTrade ? LIVE_TRADE_BLOCK : isLaunch ? 'Launch submission requires a verified launchpad adapter, signer and explicit owner authorization. Validation/preview works.' : LIVE_READ_BLOCK),
    outputExample: `{ "data": …, "meta": { "status": "simulated", "source": "jgg-fixture", "asOf": "…" } }`,
    ref: id <= 'C09' ? 'S02' : id <= 'C18' ? 'S03' : id <= 'C27' ? 'S04' : id <= 'C36' ? 'S05' : id <= 'C45' ? 'S06' : id <= 'C54' ? 'S07' : 'S08',
  } satisfies Skill;
});

export const SKILL_CATEGORIES: ('All' | SkillCategory)[] = ['All', 'Trading', 'Data Analytics', 'Monitor', 'News & Media', 'Cooking'];
