// Generates docs/REQUIREMENTS.md from this register + the skill catalog. Run: node scripts/requirements.mjs
import { writeFileSync } from 'node:fs';
const { SKILLS } = await import('../packages/catalog/src/index.ts');

const E2E = 'tests/e2e/smoke.py (17 routes × 7 viewports: 0 console errors, 0 body overflow)';
const M = [
  ['M01', '/trenches', 'apps/web/src/pages/Market.tsx (Trenches), /api/v1/markets/:stage', 'implemented_demo', 'Market data, security', `${E2E}; flow quick_buy`, 'Live feed needs GMGN/indexer credentials.'],
  ['M02', '/trending', 'Market.tsx (Trending), /api/v1/markets/:view', 'implemented_demo', 'Market data', E2E, 'Binance / NextBC / Pump Live tabs return PROVIDER_UNAVAILABLE until membership rules are verified.'],
  ['M03', '/copy-trade/:tab', 'pages/Signals.tsx (CopyTrade), /api/v1/rank, strategies kind=copy|dev_snipe|token_snipe', 'implemented_paper', 'Wallet analytics, execution', `${E2E}; tests/api T31 copy dedupe`, 'SkyEyeCopy and SnipeX: blocked (semantics unspecified in references).'],
  ['M04', '/monitor', 'Signals.tsx (Monitor + rules), apps/api/src/alerts.ts', 'implemented_demo', 'Signals', E2E, 'Telegram / web-push delivery need bot token / VAPID keys.'],
  ['M05', '/track', 'Signals.tsx (Track), /api/v1/tracked-wallets', 'implemented_demo', 'Wallet trades, social', E2E, 'SkyEye + X/TG social tabs blocked (provider).'],
  ['M06', '/portfolio', 'pages/Account.tsx (Portfolio), trading.ts portfolio/journal/export', 'implemented_paper', 'Execution, pricing', `${E2E}; flow portfolio_position; tests/api ledger`, 'Deposits/withdrawals require verified live custody.'],
  ['M07', '/rewards', 'Account.tsx (Rewards), /api/v1/rewards', 'implemented_demo', 'Fee collection, treasury', `${E2E}; tests/api T49/T55`, 'JGG fee 0 bps → zero commissions; payouts blocked.'],
  ['M08', '/up-down', 'Account.tsx (UpDown), /api/v1/up-down', 'blocked_external', 'Up/Down provider', E2E, 'Product contract/settlement/eligibility unknown.'],
  ['M09', '/perpetuals', 'Account.tsx (Perpetuals), /api/v1/derivatives/intents', 'blocked_external', 'Derivatives venue', E2E, 'No venue selected/verified; layout News/Classic present with honest empty states.'],
  ['M10', '/launch', 'Account.tsx (Launch), tools.reviewLaunch, /api/v1/launch-intents', 'implemented_demo', 'Launchpad adapters, signer', E2E, 'Validate/review works; submission CAPABILITY_BLOCKED.'],
  ['M11', '/ai', 'pages/AI.tsx, apps/api/src/tools.ts (rule planner, skill runner, API keys)', 'implemented_demo', 'LLM (optional)', `${E2E}; flows ai_run, skill_run; tests/api T38–T40`, 'No LLM key: deterministic planner, clearly labeled.'],
  ['M12', '/token/:chain/:address', 'pages/Token.tsx (canvas chart, tabs, ticket, exits)', 'implemented_paper', 'Market data, execution', `${E2E}; flow strategy_denied_without_policy`, 'Live data/execution blocked.'],
  ['M13', '/wallet/:chain/:address', 'Token.tsx (WalletPage, CopyDrawer)', 'implemented_demo', 'Wallet analytics', E2E, 'Labels are fixture rules, disclosed.'],
  ['M14', '/watchlist', 'Account.tsx (Watchlist), /api/v1/watchlists CRUD with versions', 'implemented_demo', '—', E2E, ''],
  ['M15', '/settings', 'Account.tsx (Settings: mode, presets, risk, API keys, notifications)', 'implemented_paper', '—', E2E, 'Live mode not selectable (blocked).'],
  ['M17*', '/auto (owner request 2026-09-25)', 'pages/Auto.tsx, packages/domain/src/finder.ts, strategies auto_trader, /api/v1/finder', 'implemented_paper', 'GMGN (live read-only finder)', 'tests/domain/finder.test.ts, tests/api/auto.test.ts, tests/e2e/auto_mobile.py', 'No win-rate target is promised; live data mapping unverified; live execution blocked.'],
  ['M22*', 'Finder outcome tracking (owner: verify winrate before scope growth)', 'apps/api/src/live.ts (recordFinderPasses, updateFinderOutcomes, finderOutcomeStats), /api/v1/finder/stats, Auto page panel', 'implemented_live_unverified', 'JGG indexer (no extra calls)', 'tests/api/finderOutcomes.test.ts (5 tests: pump, rug, graduation, timeout, stats)', 'No real sample yet — needs days/weeks of continuous indexing against mainnet; panel shows "—" honestly until then.'],
  ['M18*', 'Live data (owner Option B)', 'packages/providers/src/solana/*, apps/api/src/live.ts, apps/workers/src/indexer.ts', 'implemented_live_unverified', 'Solana RPC + Jupiter Price (commodity, replaceable)', 'tests/domain/pump.test.ts, tests/api/live.test.ts, tests/api/rpc.test.ts, tests/e2e/live_ui.py', 'Mainnet stream not yet verified (scripts/verify-live.mjs); Solana pump.fun bonding curve only; executions paper.'],
  ['M19*', 'FOMO labels (optional, owner request)', 'packages/providers/src/fomo.ts, indexer polling, live signals/rank label "fomo"', 'implemented_live_unverified', 'fomoapi.io (independent, unofficial; key)', 'tests/api/live2.test.ts', 'Real fomoapi.io responses not yet fetched from a networked machine.'],
  ['M20*', 'Live copy trade / snipes / wallet rank / signals (owner request)', 'apps/api/src/live.ts (liveRank, liveWalletDetail, liveSignals), strategies evalCopyLive + live snipes', 'implemented_live_unverified', 'JGG indexer', 'tests/api/live2.test.ts', 'pump.fun bonding-curve trades only; migration_buy disabled on live data.'],
  ['M21*', 'Trading wallet + live execution (real funds, owner request)', 'apps/api/src/custody.ts, packages/providers/src/solana/{tx,jupiterSwap}.ts, Settings → Trading wallet', 'implemented_live_unverified', 'Solana RPC, Jupiter Swap v2, server master key', 'tests/domain/soltx.test.ts, tests/api/custody.test.ts', 'Never run with real funds here (no network). First funded test is the owner\'s step (docs/DEPLOY.md §3.5).'],
  ['M16', '/status', 'Account.tsx (Status), /api/v1/status, /api/v1/capabilities', 'implemented_demo', '—', E2E, ''],
];
const T = [
  ['T01', 'implemented_demo', E2E + ' (deep links/refresh per route)'], ['T02', 'implemented_demo', 'catalog 66 entries; 63 run with fixtures, 3 honestly blocked (C11, C12, C42)'],
  ['T03', 'in_progress', 'docs/screenshots vs docs/reference S01–S16 inspected manually; intentional differences in docs/verification.md'],
  ['T04', 'implemented_demo', E2E], ['T05', 'implemented_demo', 'dock resize/collapse/split persisted per user + device class on the server (settings.layout) and locally; keyboard separators; tests/e2e/pwa_a11y.py layout_persisted'],
  ['T06', 'implemented_demo', 'useFrozen: order held under pointer/focus; click binds to address'], ['T07', 'implemented_demo', 'State/ErrorState/StaleBanner components; provider-unavailable & signed-out states'],
  ['T08', 'implemented_demo', 'canvas candles with explicit gaps; USD; pool shown'], ['T09', 'implemented_demo', 'tests/e2e/pwa_a11y.py: every visible control has an accessible name on 14 routes, h1 + main landmark, visible focus, "/" search; token contrast ≥5:1 (muted 5.6–6.3, neg 5.1–5.7); drawer focus trap + Esc; axe-core not run (not installable offline)'],
  ['T10', 'implemented_demo', 'fixture copycat DEMO; search warns; C03 refuses ambiguous names'], ['T11', 'implemented_demo', 'tests/domain invariants'], ['T12', 'implemented_demo', 'tests/domain fixtures A01–A07'],
  ['T13', 'implemented_demo', 'tests/domain unknown basis'], ['T14', 'implemented_paper', 'tests/api T14 (service) + Supabase RLS check as non-bypass role jgg_app'],
  ['T15', 'implemented_paper', 'fills UNIQUE(order,chain_fill_id); inbox dedupe; tests/api T31'], ['T16', 'implemented_demo', 'provenance meta on every market response; unknown ≠ 0'],
  ['T17', 'implemented_demo', 'tests/domain candle aggregation'], ['T18', 'implemented_demo', 'tests/domain ranking reproducibility'],
  ['T19', 'implemented_paper', 'tests/api "T19": replayed execute (same & different key) → one order, one fill; dispatch claim'], ['T20', 'implemented_paper', 'tests/api: key reuse with different payload → IDEMPOTENCY_KEY_REUSED'],
  ['T21', 'implemented_paper', 'tests/api T21 expired quote; mode change invalidation'], ['T22', 'implemented_paper', 'tests/api T22 two DB connections'],
  ['T23', 'implemented_paper', 'tests/api "T20": timeout → reconciliation_required, single attempt, reconcile'], ['T24', 'implemented_paper', 'tests/api T24 revert fee, no holdings'],
  ['T25', 'implemented_paper', 'exits sized from actual filled qty (tests/api T28); partial fills not modeled by paper sim'], ['T26', 'implemented_paper', 'exit coordinator claimExit (tests/domain)'],
  ['T27', 'implemented_paper', 'tests/api external reduction'], ['T28', 'implemented_paper', 'tests/domain trailing example + JSON restart'], ['T29', 'implemented_paper', 'tests/api T29 unprotected notification'],
  ['T30', 'implemented_paper', 'tests/domain copy fraction; tests/api leases'], ['T31', 'implemented_paper', 'tests/api T31'], ['T32', 'implemented_demo', 'migration_buy/dev_sell_exit on fixture events; live trigger feed blocked'],
  ['T33', 'implemented_demo', 'tests/domain batch; C50 atomic:false'], ['T34', 'implemented_paper', 'tests/api CANCEL_TOO_LATE'], ['T35', 'implemented_paper', 'tests/api kill switch'],
  ['T36', 'implemented_demo', 'tests/domain checkRisk'], ['T37', 'blocked_external', 'needs live chain adapters'], ['T38', 'implemented_demo', 'tests/api T38–T40'],
  ['T39', 'implemented_demo', 'token metadata rendered as inert text; no tool can read secrets; planner deterministic'], ['T40', 'implemented_demo', 'skill inputs validated server-side; no LLM output parsed yet'],
  ['T41', 'implemented_demo', 'tests/api HTTP SIWS replay/domain/bad-signature/nonce burn'], ['T42', 'implemented_demo', 'scripts/secret-scan.mjs'],
  ['T43', 'implemented_demo', 'tests/api/security.test.ts: 413/415/400 hardening, path traversal, https-only links, JSON+nosniff for stored text, static proof of no outbound fetch in server code; strict CSP'], ['T44', 'implemented_demo', 'tests/api/security.test.ts: B cannot read/modify A watchlists/alerts/notifications over HTTP; external channels cannot be bound (blocked)'],
  ['T45', 'blocked_external', 'social provider'], ['T46', 'blocked_external', 'launchpad adapters'], ['T47', 'blocked_external', 'derivatives venue'], ['T48', 'blocked_external', 'honestly blocked (M08)'],
  ['T49', 'implemented_demo', 'tests/api T49/T55'], ['T50', 'implemented_demo', 'apps/cli/jgg.mjs: CLI + MCP stdio server (66 skills as tools) that call the same scoped HTTP API — verified: initialize, tools/list (66), C13 → proposal awaiting approval, C52 without strategy:manage → FORBIDDEN; API-key strategies are drafts only; revocation immediate (security.test.ts)'],
  ['T51', 'in_progress', 'PROVIDER_UNAVAILABLE surfaces, no fabricated fallback; no live provider to fault-inject'], ['T52', 'implemented_demo', 'tests/api/security.test.ts: envelope fields, gap-free per-topic sequence, private topic auth + server-side filtering; slow-client resync + client backoff implemented'],
  ['T53', 'implemented_paper', 'order+attempt persisted before dispatch; dispatch claim; worker tick reconciles a crashed submission with no second attempt (security.test.ts)'], ['T54', 'implemented_paper', 'automation for a user waits while any submission is unresolved and resumes after reconciliation (security.test.ts); no real Postgres PITR drill'],
  ['T55', 'implemented_paper', 'modes separated; paper never accrues referrals'], ['T56', 'implemented_demo', 'service worker caches the shell only (never /api); offline reload shows shell + offline banner + error states; nothing queued/replayed (pwa_a11y.py)'], ['T57', 'implemented_demo', 'scripts/load-test.mjs: 3×(50 users × 20 paper trades) = 18,450 requests, ~500 rps, execute p95 ≈120 ms, 0 errors, 3,200 orders all finalized, 0 leaked reservations, API RSS plateau ≈168 MB (single node, SQLite)'],
  ['T58', 'in_progress', 'build + 45 tests + migrations reproducible offline; strict tsc typecheck passes (backend/tests/web) against offline shims for node/react types; no lockfile (npm registry blocked)'],
  ['T59', 'blocked_external', 'funded test NOT authorized; not attempted'], ['T60', 'in_progress', 'this register'],
];
const row = (xs) => `| ${xs.map(x => String(x ?? '').replace(/\|/g, '\\|')).join(' | ')} |`;
const out = [`# JGG — Requirements register`, '', `_Generated by scripts/requirements.mjs on ${new Date().toISOString().slice(0, 10)}. Statuses per spec: not_started, in_progress, implemented_demo, implemented_paper, implemented_live_unverified, verified_live, blocked_external, unsupported_by_selected_provider._`, '',
  `**Honest summary:** nothing is \`verified_live\`. Demo/Paper work end-to-end with deterministic fixture data and the disclosed paper execution model. Live data, live execution, social/news, launches, derivatives and Up/Down are blocked on external providers, credentials, a signer and owner authorization.`, '',
  '## Modules (M01–M16)', '', row(['ID', 'Route', 'Implementation', 'Status', 'Provider deps', 'Evidence', 'Remaining / blocker']), row(['---', '---', '---', '---', '---', '---', '---']), ...M.map(row), '',
  '## Skills (C01–C66)', '', 'Handlers: `apps/api/src/tools.ts` (shared by Skills Market, AI planner and API keys). Inputs validated server-side from the catalog schema.', '',
  row(['ID', 'Title', 'Category', 'Source', 'Tool', 'Demo', 'Paper', 'Live', 'Blocker']), row(['---', '---', '---', '---', '---', '---', '---', '---', '---']),
  ...SKILLS.map(s => row([s.id, s.title, s.category, s.source, '`' + s.toolId + '`', s.status.demo, s.status.paper, s.status.live, s.status.live === 'blocked_external' ? s.blocker : ''])), '',
  '## Acceptance tests (T01–T60)', '', row(['ID', 'Status', 'Evidence / note']), row(['---', '---', '---']), ...T.map(row), ''];
writeFileSync(new URL('../docs/REQUIREMENTS.md', import.meta.url), out.join('\n'));
console.log(`REQUIREMENTS.md: ${M.length} modules, ${SKILLS.length} skills, ${T.length} tests`);
